name: Coverage Gate

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: true
      - name: Run make cover
        run: make cover
      - name: Enforce >=80% coverage
        run: |
          total=$(go tool cover -func=coverage.out | awk '/^total:/{print $NF}' | tr -d '%')
          echo "Total coverage: ${total}%"
          awk -v c="$total" 'BEGIN { if (c+0 >= 80.0) exit 0; else { printf("Coverage below 80%% (%.2f%%)\n", c); exit 1 } }'
      - name: Upload coverage artifact
        if: ${{ hashFiles('coverage.out') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

