name: Test

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: true
      - name: Run tests
        run: make test
      - name: Upload coverage artifact
        if: ${{ hashFiles('coverage.out') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

